---
name: download-release-asset
description: Download release asset from Github release
inputs:
  filename:
    description: Filename of asset to download
    required: true
branding:
  color: yellow
  icon: download-cloud
runs:
  using: docker
  image: Dockerfile
  args:
  - ${{ inputs.filename }}
