#!/usr/bin/env bash

customizer="$1"
python_file="$2"
log_base="$(basename "$python_file" | sed -E 's/.py$//')"
log_file_path="$FORNIX_FOLDER/logs/$log_base$customizer.ignore.log"

echo "logging to: $log_file_path"
python "$python_file" &> "$log_file_path"