#!/usr/bin/env bash
# https://docs.nvidia.com/ai-enterprise/deployment-guide/dg-docker.html

# 
# installing docker
# 
sudo apt-get update
sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
    
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    
sudo apt-get -y update

sudo apt-get install -y docker-ce docker-ce-cli containerd.io

sudo docker run hello-world

# 
# installing nvidia-docker
# 
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit

sudo systemctl restart docker


# 
# testing
# 
sudo docker run --gpus all nvidia/cuda:11.0-base nvidia-smi