#!/usr/bin/env bash

# summary
#   this just removes all of the can-be deleted files
#   can be useful for fixing corrupted setups


# enable globbing for zsh
setopt extended_glob &>/dev/null
# enable globbing for bash
shopt -s globstar &>/dev/null
shopt -s dotglob &>/dev/null


# detach this (behaves like unlink)
rm "$PROJECTR_FOLDER/home/.cache/nix"

# the usual things
rm -rfv "$PROJECTR_FOLDER/.cache" "$PROJECTR_FOLDER/"**/*.cleanable "$PROJECTR_FOLDER/"**/*.cleanable.*
mkdir -p "$PROJECTR_FOLDER/.cache" && touch "$PROJECTR_FOLDER/.cache/.keep" # restore the keep file