#!/usr/bin/env bash
    # 
    # if projectr isnt defined, then find it
    # 
    if [ -z "$PROJECTR_FOLDER" ]
    then
        path_to_file=""
        file_name="settings/projectr_core"
        folder_to_look_in="$PWD"
        while :
        do
            # check if file exists
            if [ -f "$folder_to_look_in/$file_name" ]
            then
                path_to_file="$folder_to_look_in/$file_name"
                break
            else
                if [ "$folder_to_look_in" = "/" ]
                then
                    break
                else
                    folder_to_look_in="$(dirname "$folder_to_look_in")"
                fi
            fi
        done
        if [ -z "$path_to_file" ]
        then
            #
            # what to do if file never found
            #
            echo "Im a script running with a pwd of:$PWD"
            echo "Im looking for settings/projectr_core in a parent folder"
            echo "Im exiting now because I wasnt able to find it"
            echo "thats all the information I have"
            exit
        fi
        source "$path_to_file"
    fi


    #
    # escape all arguments
    #
    args=""
    # for each argument (in a argument-might-have-spaces friendly way)
    for arg in "$@"; do
        # this escapes single quotes
        escaped_argument="$(printf '%s' "'$(printf '%s' "$arg" | sed 's/'"'"'/'"'"'"'"'"'"'"'"'/g')'")"
        args="$args $escaped_argument"
    done
    
    name_of_executable='python3'

    # might seem like this is being escaped twice, sadly its not
    escaped_name_of_executable="$(printf '%s' "'$(printf '%s' "$name_of_executable" | sed 's/'"'"'/'"'"'"'"'"'"'"'"'/g')'")"
    args="$escaped_name_of_executable $args"
    # wrap all the args inside another arg (double escaping single quotes... yeah its gonna be 200% illegible)
    zsh_arg="$(printf '%s' "'$(printf '%s' "$args" | sed 's/'"'"'/'"'"'"'"'"'"'"'"'/g')'")"
    
    #
    # run the command, inside nix-shell, inside zsh
    #
    HOME="$PROJECTR_HOME" nix-shell --pure --run "zsh -c $zsh_arg" "$PROJECTR_FOLDER/settings/requirements/shell.nix"

